version: '3'

networks:
  webapp:
  service:

services:
  web:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    links:
      - fluentd
    volumes:
      - ./nginx/custom:/usr/share/nginx/html
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

    depends_on: [fluentd]
    networks: ['webapp']

  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks: ['service']

  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks: ['service']

  kibana:
    image: kibana
    container_name: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - service
